# Author: Amit Kumar Rajoriya
# This playbook will create the new EC2 Instance on AWS

---
  - name: Provision an EC2 Instance
    hosts: localhost
    connection: local
    gather_facts: False
    tags: provisioning

    vars:
      instance_type: t2.micro # Change the instance type
      security_group: ansible # Change the security group
      image: ami-d732f0b7 # Change the AMI
      region: us-west-2 # Change the Region
      keypair: ansible # Change the keypair name
      count: 1

    tasks:
      - name: Create New Security Group
        local_action:
          module: ec2_group
          name: "{{ security_group }}"
          description: Ansible security group
          region: "{{ region }}"
          rules:
              - proto: tcp
                from_port: 22
                to_port: 22
                cidr_ip: 0.0.0.0/0
              - proto: tcp
                from_port: 80
                to_port: 80
                cidr_ip: 0.0.0.0/0
              - proto: tcp
                from_port: 443
                to_port: 443
                cidr_ip: 0.0.0.0/0
          rules_egress:
            - proto: all
              cidr_ip: 0.0.0.0/0
        register: basic_firewall

      - name: Launch the new EC2 Instance
        local_action: ec2
                      group={{ security_group }}
                      instance_type={{ instance_type}}
                      image={{ image }}
                      region={{ region }}
                      keypair={{ keypair }}
                      count={{count}}
                      wait=True
        register: ec2

      - name: Add new instance to host group
        add_host: hostname={{ item.public_ip }} groupname=launched
        with_items: '{{ec2.instances}}'

      - name: Wait for SSH to be available
        wait_for:
          host: "{{ item.public_dns_name }}"
          port: 22
          delay: 60
          state: started
          timeout: 600
        with_items: "{{ec2.instances}}"

      - name: Set Public DNS name as env variable
        shell: "export MY_DNS_NAME={{ item.public_dns_name }}"
        with_items: "{{ec2.instances}}"
